services:
  localstack:
    image: localstack/localstack:4.14
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,iam
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cognito-local:
    image: jagregory/cognito-local
    ports:
      - "9229:9229"

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
      - cognito-local
    volumes:
      - ./scripts/init-local-aws.sh:/init-local-aws.sh
      - ./:/workspace
      - ../packages:/packages
    entrypoint: /bin/sh
    command: /init-local-aws.sh
volumes:
  cognito_data:
