services:
  localstack:
    image: localstack/localstack:4.14
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cognito-local:
    image: jagregory/cognito-local
    ports:
      - "9229:9229"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack

  s3manager:
    image: cloudlena/s3manager:latest
    ports:
      - "8002:8080"
    environment:
      - ENDPOINT=localstack:4566
      - REGION=us-east-1
      - ACCESS_KEY_ID=test
      - SECRET_ACCESS_KEY=test
      - USE_SSL=false
    depends_on:
      - localstack

  aws-cli:
    image: amazon/aws-cli
    depends_on:
      - localstack
      - cognito-local
    volumes:
      - ./scripts/init-local-aws.sh:/init-local-aws.sh
      - ./:/workspace
      - ../packages:/packages
    entrypoint: /bin/sh
    command: /init-local-aws.sh
volumes:
  cognito_data:
